services:
  - type: web
    name: hotspot-backend
    env: node
    buildCommand: ./build.sh
    startCommand: cd backend && npm prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hotspot-db
          property: connectionString

databases:
  - name: hotspot-db
    plan: free 